# =========================
# DATABASE CONFIGURATION
# =========================
spring.datasource.url=jdbc:mysql://localhost:3306/placementprep
spring.datasource.username=root
spring.datasource.password=@Dhruv_64

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Hibernate automatically MySQL dialect detect kar lega
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# =========================
# SERVER CONFIGURATION
# =========================
server.port=${PORT:8080}